apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    demo: service
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port